config/routes.rb
Rails.application.routes.draw do
  get 'secrets' => 'secrets#index'
  get 'users/new'
  post '/register' => 'users#create'
  get 'users/show'
  get 'users/:user_id/edit' => 'users#edit'
  post '/update' => 'users#update'
  post '/destroy/:user_id' => 'users#destroy'
  get 'users/:user_id' => 'users#index'
  post '/secret' => 'secrets#create'
  post '/secret/destroy/:secret_id' => 'secrets#destroy'
  post '/liked/:secret_id' => 'secrets#liked'
  get 'sessions/new'
  post '/sessions' => 'sessions#create'
  delete '/sessions/:user_id' => 'sessions#destroy'

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :secret
end

app/models/secret.rb
class Secret < ActiveRecord::Base
  belongs_to :user
  has_many :likes
  validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :secrets
  has_many :likes, dependent: :destroy
  has_many :secrets_liked, through: :likes, source: :secret
  has_secure_password
  validates :name, :email, presence: true
  validates :email, uniqueness: true, format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }
  before_create do
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  def index
    @secrets = Secret.all
  end
  def create
    @secret = User.find(current_user.id).secrets.new(content: params[:Content])
    if @secret.save
      redirect_to "/users/#{current_user.id}"
    else
      flash[:errors] = @secret.errors.full_messages
      redirect_to "/users/#{current_user.id}"
    end
  end
  def liked
    if params[:secret] == "like"
      User.find(current_user.id).likes.create(secret:Secret.find(params[:secret_id]))
    end
    if params[:secret] == "unlike"
      User.find(current_user.id).likes.find(secret: Secret.find(params[:secret_id])).destroy
    end
    redirect_to secrets_path
  end
  def destroy
    Secret.find(params[:secret_id]).destroy
    redirect_to "/users/#{current_user.id}"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    if User.find_by_email(params[:email]).try(:authenticate, params[:password])
      session[:user_id] = User.find_by_email(params[:email]).id
      redirect_to "/users/#{current_user.id}"
    else
      flash[:errors] = ["Invalid Combination"]
      redirect_to sessions_new_path
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to sessions_new_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
  def new
    session[:user_id] = nil
  end
  def create
    @user = User.new(params.require(:user).permit(:name, :email, :password, :password_confirmation))
    if @user.save
      session[:user_id] = @user.id
      redirect_to sessions_new_path
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to users_new_path
    end
  end
  def show
  end
  def edit
  end
  def update
    @user = User.update(current_user.id, params.require(:user).permit(:name, :email, :password, :password_confirmation))
    if @user.save
      redirect_to "/users/#{current_user.id}/edit"
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to "/users/#{current_user.id}/edit"
    end
  end
  def destroy
    User.find(current_user.id).destroy
    redirect_to users_new_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DojoSecrets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if flash[:errors] %>
    <% flash[:errors].each do |e| %>
      <%= e %>
    <% end %>
  <% end %>
  <% if current_user %>
    <form action="/sessions/<%=current_user.id%>" method="post">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <input type="hidden" name="_method" value="delete">
      <input type="submit" value="Log Out">
    </form>
  <% end %> 

  <%= yield %>

</body>
</html>

app/views/secrets/index.html.erb
<a href="/users/<%= current_user.id %>">View My Secrets</a>
<% @secrets.each do |secret| %>
    <p><%= secret.content %></p>
    <p><%= secret.likes.count %> likes</p>
    <% if current_user.secrets_liked_ids.include? secret.id %>
        <form action="/liked/<%= secret.id %>" method="post">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input type="hidden" name="secret" value="unlike">
            <input type="submit" value="Unlike">
        </form>
    <% else %>
        <form action="/liked/<%= secret.id %>" method="post">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input type="hidden" name="secret" value="like">
            <input type="submit" value="Like">
        </form>
    <% end %>
    <% if current_user == secret.user %>
        <form action="/secret/destroy/<%= secret.id %>" method="post">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input type="submit" value="Delete Secret">
        </form>
    <% end %>
<% end %>

app/views/users/edit.html.erb
<a href="/users/<%= current_user.id %>">View My Secrets</a>
<h3><%= current_user.name %></h3>
<form action="/update" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label for="name">Name</label>
    <input type="text" name="user[name]" id="name" value="<%= current_user.name %>">
    <label for="email">Email</label>
    <input type="text" name="user[email]" id="email" value="<%= current_user.email %>">
    <input type="submit" value="Update">
</form>
<form action="/destroy/<%= current_user.id %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="submit" value="Delete Account">
</form>

app/views/users/index.html.erb
<p><%= current_user.name %>   <a href="/secrets">View All Secrets</a></p>
<a href='/users/<%= current_user.id %>/edit'>Edit Profile</a>
<form action='/secret' method='post'>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label for="Content">New Secret</label>
    <textarea name="Content" id="Content"></textarea>
    <input type="submit" value="Create Secret">
</form>
<p>Secrets</p>
<% current_user.secrets.each do |secret| %>
    <% if secret.id == current_user.secrets.last.id %>
        <p>My new secret</p>
        <%= secret.content %>
    <% end %>
    <% unless secret.id == current_user.secrets.last.id %>
        <%= secret.content %>
    <% end %>
    <form action='/secret/destroy/<%= secret.id %>' method='post'>
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="submit" value="Delete Secret">
    </form>
<% end %>

app/views/users/new.html.erb
<form action="/register" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label for="name">Name</label>
    <input type="text" name="user[name]" id="name">
    <label for="email">Email</label>
    <input type="text" name="user[email]" id="email">
    <label for="password">Password</label>
    <input type="password" name="user[password]" id="password">
    <label for="password_confirmation">Password_Confirmation</label>
    <input type="password" name="user[password_confirmation]" id="password_confirmation">
    <input type="submit" value="Join">
</form>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>